name: Delete branch
on:
  workflow_dispatch:
jobs:
  cleanup-branches:
    runs-on: ubuntu-latest
    steps:
      # To use this action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cleanup
        uses: digicert/prune_old_branches_action@v1
        with:
          numDays: '200'
          numTags: '3'
